// <auto-generated />
namespace Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DestinationDescription_Original_Changesize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DestinationDescription_Original_Changesize));
        
        string IMigrationMetadata.Id
        {
            get { return "201706080241426_Destination.Description_Original_Changesize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
